version: "3.8"

services:
  postgres:
    restart: always
    container_name: postgres
    image: postgres:16
    networks:
      - shared_network
    # env_file: ./.env
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - ${DATA_DIR}/pgdata:/var/lib/postgresql/data
  portainer:
    image: portainer/portainer-ce
    container_name: portainer
    restart: always
    networks:
      - shared_network
    ports:
      - 9000:9000
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data
  redis:
    image: redis:6.2
    container_name: redis
    restart: always
    networks:
      - shared_network
    ports:
      - 6370:6370
    environment:
      - REDIS_PASSWORD=${DB_PASSWORD}
  mongo:
    image: mongo
    container_name: mongo
    restart: always
    networks:
      - shared_network
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${DB_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${DB_PASSWORD}
    volumes:
      - ${DATA_DIR}/mongo:/data/db

volumes:
  portainer_data:
networks:
  shared_network:
    external: true