version: '3.8'
services:
  
  postgres:
    build: ./postgresql
    restart: always
    container_name: postgres_db
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - ${DATA_DIR}/pgdata:/var/lib/postgresql/data 
      - ./postgresql/conf/postgresql.conf:/etc/postgresql/postgresql.conf # Mount custom pg.conf
  
  redis:
    build: ./redis
    restart: always
    container_name: redis
    ports:
      - 6379:6379
    volumes:
      - ${DATA_DIR}/redis:/data
      - ./redis/conf/redis.conf:/usr/local/etc/redis/redis.conf  # Custom Redis configuration 
  
  portainer:
    build: ./portainer
    restart: always
    container_name: portainer
    ports:
      - 9000:9000
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

# volumes:
#   pgdata: