name: DB CI
on: [push,]
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout latest Code
      uses: actions/checkout@v3
      with:
        path: sass-db-services
    - name: Copy files to Server
      uses: appleboy/scp-action@master
      with:
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        source: "sass-db-services,!sass-db-services/.git,!sass-db-services/.github"
        overwrite: true
        host: ${{ secrets.REMOTE_HOST }}
        username: ${{ secrets.REMOTE_USER }}
        port: ${{ secrets.HOST_PORT }}
        target: ${{ secrets.REMOTE_TARGET }}
        
    - name: Deploy code to Server
      uses: appleboy/ssh-action@master
      with:
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          # source: "sass-db-services"
          host: ${{ secrets.REMOTE_HOST }}
          username: ${{ secrets.REMOTE_USER }}
          port: ${{ secrets.HOST_PORT }}
          # target: ${{ secrets.REMOTE_TARGET }}
          script: |
            cd ~/apps/sass-db-services
            docker compose up --build -d
      


